<a href="https://colab.research.google.com/github/dilrabonu/python-step1/blob/main/Arifmetik_amallar1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
arr1= np.arange(6). reshape(2, 3)
arr2= np.arange(6, 12).reshape(2, 3)

In [4]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
arr1+arr2 # mos ravishda qo'shadi

array([[ 6,  8, 10],
       [12, 14, 16]])

In [7]:
arr1*arr2 # mos ravishda ko'paytiradi

array([[ 0,  7, 16],
       [27, 40, 55]])

In [8]:
arr1/arr2 # mos ravishda bo'ladi

array([[0.        , 0.14285714, 0.25      ],
       [0.33333333, 0.4       , 0.45454545]])

In [9]:
arr2-arr1 # mos ravishda ayiradi

array([[6, 6, 6],
       [6, 6, 6]])

In [10]:
arr1**2 # arr1 ning kvadrati (square)

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [11]:
arr2**3 #arr2 ning kubi

array([[ 216,  343,  512],
       [ 729, 1000, 1331]])

In [12]:
arr1**0.5 #arr1 ning kvadrat ildizi (sqrt)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])