<a href="https://colab.research.google.com/github/dilrabonu/python-step1/blob/main/binary_funksiyalar2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
arr2=np.random.randn(6)
arr3=np.random.randn(6)


In [4]:
arr2

array([ 0.89001401,  1.03782354,  1.26255002,  0.79328323, -1.12905142,
       -0.62337461])

In [5]:
arr3

array([-0.76336085, -0.45802991, -0.55945778, -0.48505172,  0.23713974,
       -0.21970781])

In [6]:
np.add(arr2, arr3) # arr2 va arr3 ni mos ravishda qo'shib beradi

array([ 0.12665316,  0.57979363,  0.70309225,  0.30823151, -0.89191168,
       -0.84308242])

In [7]:
arr2+arr3 # yuqoridagi array bn bir xil

array([ 0.12665316,  0.57979363,  0.70309225,  0.30823151, -0.89191168,
       -0.84308242])

In [8]:
np.multiply(arr2, arr3) # arr2 va 3 ni mos ravishda ko'paytiradi

array([-0.67940185, -0.47535422, -0.70634343, -0.38478339, -0.26774296,
        0.13696027])

In [9]:
np.maximum(arr2, arr3) # 2ta massivni taqqoslab katta qiymatini qaytaradi

array([ 0.89001401,  1.03782354,  1.26255002,  0.79328323,  0.23713974,
       -0.21970781])

In [10]:
np.minimum(arr2, arr3) # taqqoslab kichigini qaytaradi

array([-0.76336085, -0.45802991, -0.55945778, -0.48505172, -1.12905142,
       -0.62337461])

In [12]:
np.fmax(arr2, arr3) # bu ham kattasini qaytaradi

array([ 0.89001401,  1.03782354,  1.26255002,  0.79328323,  0.23713974,
       -0.21970781])