<a href="https://colab.research.google.com/github/dilrabonu/python-step1/blob/main/boolean_index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [7]:
#Ismlar
names= np.array (['Dilrabo', 'Iqbol', 'Iftihorbek', 'Farzonabonu','Iqbol', 'Ismoilbek',  'Iftihorbek'])
names

array(['Dilrabo', 'Iqbol', 'Iftihorbek', 'Farzonabonu', 'Iqbol',
       'Ismoilbek', 'Iftihorbek'], dtype='<U11')

In [9]:
#data
data=np.random.randn(7,4)
data

array([[-2.20442072,  0.14554725,  0.02415951,  0.62988298],
       [ 1.40363421,  0.71210121, -0.11155355,  0.96311361],
       [-0.86927461, -0.31902813,  0.31043235, -1.09269996],
       [-0.00922377, -0.23160146, -0.42032713, -0.8563358 ],
       [-1.08248599,  0.67119646,  2.11302618, -0.35918109],
       [ 0.6227708 , -0.62959237, -0.81319168,  0.57811112],
       [-0.14614854,  0.3920003 , -0.82168245,  1.51257983]])

In [10]:
names == "Iqbol"

array([False,  True, False, False,  True, False, False])

In [11]:
data [names == "Iqbol"] # iqbolga tegishli barcha malumotlarni ajratamiz boolen orqali

array([[ 1.40363421,  0.71210121, -0.11155355,  0.96311361],
       [-1.08248599,  0.67119646,  2.11302618, -0.35918109]])

In [12]:
data [names == "Ismoilbek"]

array([[ 0.6227708 , -0.62959237, -0.81319168,  0.57811112]])

In [13]:
data [names== "Iqbol", 2:] #Iqbolni ichidagi oxirgi ma'lumotlar

array([[-0.11155355,  0.96311361],
       [ 2.11302618, -0.35918109]])

In [14]:
data [names!= "Iqbol"] # Iqbolga tegishli bo'lmagan barcha ma'lumotlarni ko'rsatadi

array([[-2.20442072,  0.14554725,  0.02415951,  0.62988298],
       [-0.86927461, -0.31902813,  0.31043235, -1.09269996],
       [-0.00922377, -0.23160146, -0.42032713, -0.8563358 ],
       [ 0.6227708 , -0.62959237, -0.81319168,  0.57811112],
       [-0.14614854,  0.3920003 , -0.82168245,  1.51257983]])

In [15]:
data [~(names== "Iqbol")] # ~ bu belgi bn ham Iqbolga tegishli bo'lmagan barcha ma'lumotlarni chiqarish un foydalanamiz

array([[-2.20442072,  0.14554725,  0.02415951,  0.62988298],
       [-0.86927461, -0.31902813,  0.31043235, -1.09269996],
       [-0.00922377, -0.23160146, -0.42032713, -0.8563358 ],
       [ 0.6227708 , -0.62959237, -0.81319168,  0.57811112],
       [-0.14614854,  0.3920003 , -0.82168245,  1.51257983]])

In [16]:
print (names)
print (data)

['Dilrabo' 'Iqbol' 'Iftihorbek' 'Farzonabonu' 'Iqbol' 'Ismoilbek'
 'Iftihorbek']
[[-2.20442072  0.14554725  0.02415951  0.62988298]
 [ 1.40363421  0.71210121 -0.11155355  0.96311361]
 [-0.86927461 -0.31902813  0.31043235 -1.09269996]
 [-0.00922377 -0.23160146 -0.42032713 -0.8563358 ]
 [-1.08248599  0.67119646  2.11302618 -0.35918109]
 [ 0.6227708  -0.62959237 -0.81319168  0.57811112]
 [-0.14614854  0.3920003  -0.82168245  1.51257983]]


In [19]:
mask = (names== "Iqbol") | (names == "Dilrabo") # | belgi or yoki degan ma'noni beradi
mask

array([ True,  True, False, False,  True, False, False])

In [20]:
data [mask] # Iqbol va Dilraboga tegishli ma'lumotlarni chaqirib berdi

array([[-2.20442072,  0.14554725,  0.02415951,  0.62988298],
       [ 1.40363421,  0.71210121, -0.11155355,  0.96311361],
       [-1.08248599,  0.67119646,  2.11302618, -0.35918109]])

In [22]:
data [data<0]

array([-2.20442072, -0.11155355, -0.86927461, -0.31902813, -1.09269996,
       -0.00922377, -0.23160146, -0.42032713, -0.8563358 , -1.08248599,
       -0.35918109, -0.62959237, -0.81319168, -0.14614854, -0.82168245])

In [23]:
data [data<0]= 0
data

array([[0.        , 0.14554725, 0.02415951, 0.62988298],
       [1.40363421, 0.71210121, 0.        , 0.96311361],
       [0.        , 0.        , 0.31043235, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.67119646, 2.11302618, 0.        ],
       [0.6227708 , 0.        , 0.        , 0.57811112],
       [0.        , 0.3920003 , 0.        , 1.51257983]])