<a href="https://colab.research.google.com/github/dilrabonu/python-step1/blob/main/dytpe_astype.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
arr1= np.array([2, 4, 6], dtype= np.float64)
arr1

array([2., 4., 6.])

In [5]:
arr2= np.array ([1, 2, 3], dtype = np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [6]:
arr1.dtype

dtype('float64')

In [7]:
arr2.dtype

dtype('int32')

In [9]:
float_arr= arr2.astype (np.float64)
float_arr

array([1., 2., 3.])

In [10]:
float_arr.dtype

dtype('float64')

In [12]:
data =np.array ([1.2, 3.6, 7.9, 4])
data

array([1.2, 3.6, 7.9, 4. ])

In [14]:
data.dtype

dtype('float64')

In [15]:
int_data= data.astype (np.int64)
int_data

array([1, 3, 7, 4])

In [16]:
int_data.dtype

dtype('int64')