<a href="https://colab.research.google.com/github/dilrabonu/python-step1/blob/main/fayllar_bilan_ish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.save("data", arr)

In [4]:
np.load("data.npy") # saqlangan faylni oqish un

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2=np.load("data.npy")
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr1=np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
np.savez("arrays", a=arr, b=arr1)


# Новый раздел

In [13]:
arrays=np.load("arrays.npz")


In [15]:
arrays["a"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arrays["b"]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])