<a href="https://colab.research.google.com/github/dilrabonu/python-step1/blob/main/indekslash%2C_kesish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
arr= np.arange(10, 100, 10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
arr[1] #indeks ko'rsatish

20

In [5]:
arr[-4] #teskari indeksni korsatadi

60

In [6]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [7]:
arr[3:5] # 3dan 5gacha indeksni kesadi 5 kirmaydi

array([40, 50])

In [8]:
arr [-6:-2] #teskari indeksni kesish

array([40, 50, 60, 70])

In [9]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
sliced_arr= arr [3:5]
sliced_arr [:]= 0 # kesilgan sonlarni 0 ga tenglashtiramiz
sliced_arr

array([0, 0])

In [11]:
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [ ]:
copy usulidan foydalanish

In [13]:
arr1= np.arange (10, 100, 10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
sliced_arr1 = arr [3:5].copy()
sliced_arr1 [:]= 0
sliced_arr1

array([0, 0])

In [16]:
arr1 # copy usulidan foydalanganimiz uchun 40 va 50 o'zgarmadi

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [17]:
arr2d= np.array ([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr2d [1, 1] #qator va ustun kiritiladi

5

In [19]:
arr2d [2,2]

9

In [20]:
sl_arr2d= arr2d [1, 1:3] # 2 o'lchamli bir nechta elementlarni kesish qatori va ustuni kiritiladi
sl_arr2d

array([5, 6])

In [23]:
arr3d= np.array ([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]],

                  [[9,10,11],
                   [12, 13, 14],
                   [15, 16, 17]],

                  [[18, 19, 20],
                   [21, 22, 23],
                   [24, 25, 26]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [24]:
arr3d [0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr3d [0] [1,1]

5

In [28]:
arr3d [1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [29]:
arr3d [2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [31]:
arr3d [2][0, :2]

array([18, 19])

In [32]:
arr3d [2][1:2]

array([[21, 22, 23]])

In [33]:
arr3d [2] [0:2,2]

array([20, 23])

In [34]:
arr3d [0] [1]

array([4, 5, 6])