<a href="https://colab.research.google.com/github/dilrabonu/python-step1/blob/main/matematik_statistik_amallar1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
arr=np.random.randn(5, 4)
arr

array([[ 0.54677125, -0.92334527,  1.41903824, -1.8991163 ],
       [-1.15378719, -0.10245013, -0.76804448, -0.22649027],
       [-1.44830675,  1.34573921,  0.32556438,  0.36789746],
       [ 1.82235951, -0.13759067,  1.11704117, -0.85385184],
       [-0.18043046, -0.32892807,  1.07753683, -1.82123904]])

In [7]:
arr.sum() # barcha elementlar yigindisini korsatadi

-1.821632420311734

In [8]:
#yoki
np.sum(arr) # yuqoridagi amal bn bir xil

-1.821632420311734

In [9]:
arr.sum(axis=1) #qator ya'ni gorizontal malumotlarni qo'shadi qator 5ta

array([-0.85665207, -2.25077207,  0.59089431,  1.94795816, -1.25306074])

In [10]:
arr.sum(axis=0) # ustun boyicha elementlarnin qo'shadi ustun 4ta

array([-0.41339365, -0.14657493,  3.17113614, -4.43279998])

In [11]:
data=np.arange(5)
data

array([0, 1, 2, 3, 4])

In [12]:
mean= np.sum(data)/ len(data) # pythonda hisoblash
mean

2.0

In [14]:
np.mean(data) # numpy da hisoblash


2.0

In [15]:
#yoki
data.mean()

2.0

In [16]:
arr

array([[ 0.54677125, -0.92334527,  1.41903824, -1.8991163 ],
       [-1.15378719, -0.10245013, -0.76804448, -0.22649027],
       [-1.44830675,  1.34573921,  0.32556438,  0.36789746],
       [ 1.82235951, -0.13759067,  1.11704117, -0.85385184],
       [-0.18043046, -0.32892807,  1.07753683, -1.82123904]])

In [17]:
np.mean(arr)# arrning o'rtacha qiymati

-0.0910816210155867

In [18]:
arr.mean()

-0.0910816210155867

In [19]:
np.mean(arr, axis=1) # qator boyicha elementlarning o'rtacha qiymati

array([-0.21416302, -0.56269302,  0.14772358,  0.48698954, -0.31326519])

In [20]:
# yoki
arr.mean(axis=1)

array([-0.21416302, -0.56269302,  0.14772358,  0.48698954, -0.31326519])

In [21]:
np.mean(arr, axis=0) # bunda ustun bo'yicha nma'lumotlar qiymatini ko'rsatadi

array([-0.08267873, -0.02931499,  0.63422723, -0.88656   ])

In [22]:
#yoki
arr.mean (axis=0)

array([-0.08267873, -0.02931499,  0.63422723, -0.88656   ])

In [23]:
data

array([0, 1, 2, 3, 4])

In [25]:
data.cumsum() # orinma o'rin qo'shib yozib ketadi

array([ 0,  1,  3,  6, 10])