<a href="https://colab.research.google.com/github/dilrabonu/python-step1/blob/main/numpy_array1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
data1= [3.5, 5, 6, 2]
arr1 = np.array (data1)

In [3]:
arr1

array([3.5, 5. , 6. , 2. ])

In [4]:
data2= (4 , 5, 6, 7)
arr2= np.array(data2)

In [5]:
arr2

array([4, 5, 6, 7])

In [6]:
arr1.ndim

1

In [7]:
arr2.ndim

1

In [8]:
data3= [[1,2,3,4], [5, 6, 7, 8]]
arr3=np.array(data3)

In [9]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr3.ndim

2

In [11]:
arr3.shape

(2, 4)

In [12]:
arr3.size

8

In [13]:
arr4= np.zeros (shape= (2,4))

In [14]:
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
arr5=np.ones ((2,4)
arr5)

SyntaxError: ignored

In [17]:
arr5=np.ones ((2,4))

In [18]:
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
arr6=np.arange (4,20,2)
arr6

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
arr7= np.arange(20)
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])