<a href="https://colab.research.google.com/github/dilrabonu/python-step1/blob/main/sorting_tartiblash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#data
arr=np.random.rand(4)
arr

array([0.17469754, 0.80127951, 0.77075569, 0.0811155 ])

In [3]:
#1usul
sorted_arr= np.sort(arr) # arrning tartiblangan versiyasi
sorted_arr

array([0.0811155 , 0.17469754, 0.77075569, 0.80127951])

In [4]:
#2 usul
arr.sort() # arrning tartiblangan ko'rinishi
arr

array([0.0811155 , 0.17469754, 0.77075569, 0.80127951])

In [5]:
arr1=np.random.rand(6)
arr1

array([0.33235777, 0.25327908, 0.20013938, 0.68819908, 0.50456054,
       0.17698824])

In [6]:
sorted_arr1=np.sort(arr1)
sorted_arr1

array([0.17698824, 0.20013938, 0.25327908, 0.33235777, 0.50456054,
       0.68819908])

In [7]:
arr1.sort()
arr1

array([0.17698824, 0.20013938, 0.25327908, 0.33235777, 0.50456054,
       0.68819908])

In [8]:
rev_arr = -np.sort(-arr) # teskari tartiblash
rev_arr

array([0.80127951, 0.77075569, 0.17469754, 0.0811155 ])

In [9]:
rev_arr1= -np.sort(-arr1)
rev_arr1

array([0.68819908, 0.50456054, 0.33235777, 0.25327908, 0.20013938,
       0.17698824])

In [10]:
arr2d= np.random.randn(2, 4)
arr2d

array([[-0.70366114,  1.14422155,  0.22979118,  1.52199107],
       [-1.13501219,  0.04108172, -1.10469261,  1.90609971]])

In [11]:
row_srt= np.sort(arr2d, axis=0) # ustrun bo'yicha tartiblaymiz
row_srt

array([[-1.13501219,  0.04108172, -1.10469261,  1.52199107],
       [-0.70366114,  1.14422155,  0.22979118,  1.90609971]])

In [12]:
col_srt= np.sort(arr2d, axis=1) # qator bo'yicha tartiblash
col_srt

array([[-0.70366114,  0.22979118,  1.14422155,  1.52199107],
       [-1.13501219, -1.10469261,  0.04108172,  1.90609971]])

In [14]:
col_srt_rev= -np.sort(-arr2d, axis=1) #teskari tartiblash
col_srt_rev

array([[ 1.52199107,  1.14422155,  0.22979118, -0.70366114],
       [ 1.90609971,  0.04108172, -1.10469261, -1.13501219]])