<a href="https://colab.research.google.com/github/dilrabonu/python-step1/blob/main/Task2Numpy_d_xidirova1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr= np.arange(9).reshape(3, 3) # task 1
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
arr
arr[2, 0:2] #task2

array([6, 7])

In [7]:
arr2d= np.array ([[[ 0,  1,  2], # task 3
                [ 3,  4,  5],
                [ 6,  7,  8]],

               [[ 9, 10, 11],
                [12, 13, 14],
                [15, 16, 17]],

               [[18, 19, 20],
                [21, 22, 23],
                [24, 25, 26]]])
arr2d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [30]:
arr2d [1][1, 0:2]


array([12, 13])

In [31]:
arr2d[1] [2, 0:2]

array([15, 16])

In [39]:
names=np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U7')

In [45]:
data=np.array([[5, 6, 1, 1],
   [9, 1, 1, 1],
   [7, 7, 4, 2],
   [1, 5, 1, 9],
   [9, 9, 4, 5],
   [7, 5, 9, 6],
   [5, 3, 7, 4]])
data

array([[5, 6, 1, 1],
       [9, 1, 1, 1],
       [7, 7, 4, 2],
       [1, 5, 1, 9],
       [9, 9, 4, 5],
       [7, 5, 9, 6],
       [5, 3, 7, 4]])

In [46]:
data[names== "Javohir"]

array([[7, 7, 4, 2],
       [7, 5, 9, 6]])

In [47]:
data[names== "Elyor"]

array([[1, 5, 1, 9],
       [5, 3, 7, 4]])

In [48]:
mask = (names=="Javohir")| (names=="Elyor")
data [mask]

array([[7, 7, 4, 2],
       [1, 5, 1, 9],
       [7, 5, 9, 6],
       [5, 3, 7, 4]])