<a href="https://colab.research.google.com/github/dilrabonu/python-step1/blob/main/transposing_swaping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A= np.arange (6)
A

array([0, 1, 2, 3, 4, 5])

In [3]:
A= np.arange (6).reshape (3, 2) # A massiv elementlari 0dan 6 gacha shape 3 dan 2 ga
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
A.T # A massivning tranpose shaklini beradi

array([[0, 2, 4],
       [1, 3, 5]])

In [5]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
A.swapaxes (1, 0)  #A massivning tranpose shaklini beradi faqat kop o'lchamlar un ishlatishimiz mn

array([[0, 2, 4],
       [1, 3, 5]])

In [7]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
np.dot(A, A.T) # A va A ning transposedan hosil bo'lgan massiv ko'paytma ya'ni

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])