<a href="https://colab.research.google.com/github/dilrabonu/python-step1/blob/main/Unary_funksiyalat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
arr=np.arange(10) # 0 dan 10 gacha massiv qaytaradi
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr) # arraydan ildizlarini  qaytaradi

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.square(arr)# array nomli barcha elementlarini kv ga oshirib

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
np.exp(arr) # arrayning barcha elementlarini exponentinini qaytaradi

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [8]:
np.log(arr[1:]) # arr ning 0 dan tashqaribarcha elementlarini logarifmini hisoblaydi

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [9]:
arr1= np.random.randn(6) # 6 ta elementdan iborat taxminiy elementlar
arr1

array([ 0.84090975, -0.4707224 , -1.22058497,  0.71032686,  0.04943282,
       -1.0334698 ])

In [10]:
qoldiq, butun= np.modf(arr1) # butun va qoldiqqa arr1 ni ajratadi

In [11]:
print (qoldiq)
print (butun)

[ 0.84090975 -0.4707224  -0.22058497  0.71032686  0.04943282 -0.0334698 ]
[ 0. -0. -1.  0.  0. -1.]


In [12]:
np.sign(arr1) #arr1 ni -1 va 1 shaklida qaytaradi

array([ 1., -1., -1.,  1.,  1., -1.])

In [13]:
arr1

array([ 0.84090975, -0.4707224 , -1.22058497,  0.71032686,  0.04943282,
       -1.0334698 ])

In [14]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [15]:
arr1 [0] =np.NaN # 0 elementni NaN ga aylantirib oldik
arr1

array([        nan, -0.4707224 , -1.22058497,  0.71032686,  0.04943282,
       -1.0334698 ])

In [16]:
np.isnan(arr1)

array([ True, False, False, False, False, False])