<a href="https://colab.research.google.com/github/dilrabonu/python-step1/blob/main/Where_shart1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
xarr= np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr=np.array ([2.1, 2.2, 2.3, 2.4, 2.5])

In [3]:
#shart
cond=np.array ([True, False, True, True, False])


In [4]:
#where
result= np.where(cond, xarr, yarr) #cond==True bolsa-xarr, cond==false bo'lsa-yarr
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [5]:
arr=np.random.randn (4, 4) # (4, 4) taxminiy massiv yaratish
arr

array([[ 0.48440715, -0.81790166, -0.35445934, -0.47235799],
       [ 0.14753632, -0.4938588 , -0.59662991,  0.70911289],
       [-0.23976222,  0.80437478, -2.08986677, -1.02189418],
       [-0.57736972,  0.95475858, -0.4880131 , -0.8887362 ]])

In [6]:
results= np.where(arr<0, -2, 2) # arr ning manfiylarini -2 ga, musbatlarni esa2 ga aylantiradi
results

array([[ 2, -2, -2, -2],
       [ 2, -2, -2,  2],
       [-2,  2, -2, -2],
       [-2,  2, -2, -2]])

In [7]:
arr1=np.random.randn (5, 5)
arr1

array([[-0.96660643,  0.46092945, -0.07339273,  0.46901897, -0.28456878],
       [-0.39541544, -0.51645555,  2.6498604 ,  0.73357814,  1.0912341 ],
       [ 0.0291691 ,  1.94387881,  1.86753247, -0.17214788, -1.48354479],
       [ 1.47848176, -0.71727612,  1.24245305,  0.2194312 ,  0.30441966],
       [ 1.39813433,  1.98165931,  0.90491402, -0.66584396, -0.9098139 ]])

In [8]:
r=np.where(arr1>0, 5, 3)
r

array([[3, 5, 3, 5, 3],
       [3, 3, 5, 5, 5],
       [5, 5, 5, 3, 3],
       [5, 3, 5, 5, 5],
       [5, 5, 5, 3, 3]])