<a href="https://colab.research.google.com/github/dilrabonu/python-step1/blob/main/Yakuniyu_%22mohirdev_NumPy_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [ ]:
import numpy as np
np.show_config
np.__config__.show()

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
arr=np.array([1, 2, 3, 4, 5])
arr


array([1, 2, 3, 4, 5])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [ ]:
arr1= np.zeros(shape=(1,10))
arr1


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
arr2= np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2.size

10

In [ ]:
arr2.itemsize

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
np.info(np.add())

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
arr3=np.arange(12)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr3=np.zeros(12)
arr3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr3[6]=1
arr3

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
arr4= np.arange (20, 59)
arr4

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
arr4

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

In [ ]:
rev_arr=-np.sort(-arr4)
rev_arr

array([58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42,
       41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25,
       24, 23, 22, 21, 20])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
arr5= np.arange(11,20).reshape(3, 3)
arr5

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
arr6=np.array([3, 7, 0, 0, 9, 0])
arr6
np.nonzero(arr6)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
arr7= np.random.random (2*2*2)
arr7

array([0.49337811, 0.56398312, 0.88118696, 0.21888453, 0.46145588,
       0.22194515, 0.90919202, 0.72734662])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
arr8= np.random.random(9)
arr8

array([0.58079347, 0.51225056, 0.84214215, 0.94611776, 0.33376897,
       0.92881686, 0.49149978, 0.25247701, 0.31919993])

In [ ]:
arr9=np.random.random(9)
arr9

array([0.8014307 , 0.90760284, 0.23323604, 0.04558306, 0.82089785,
       0.79779293, 0.49470348, 0.97054113, 0.87673779])

In [ ]:
np.maximum(arr8, arr9)

array([0.8014307 , 0.90760284, 0.84214215, 0.94611776, 0.82089785,
       0.92881686, 0.49470348, 0.97054113, 0.87673779])

In [ ]:
np.minimum (arr8, arr9)

array([0.58079347, 0.51225056, 0.23323604, 0.04558306, 0.33376897,
       0.79779293, 0.49149978, 0.25247701, 0.31919993])

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
A=np.arange(18).reshape (6, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
B=np.arange(12).reshape (3,4)
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.dot(A, B)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218],
       [164, 203, 242, 281],
       [200, 248, 296, 344]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
10

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
a= np.array ([1,2])
a

array([1, 2])

In [ ]:
b= np.array ([4,5])
b

array([4, 5])

In [ ]:
print("Array a: ", a)
print("Array b: ", b)



Array a:  [1 2]
Array b:  [4 5]


In [ ]:
print ("a>b")
print (np.greater (a,b))

a>b
[False False]


In [ ]:
print("a>=b")
print (np.greater_equal(a, b))

a>=b
[False False]


In [ ]:
print ("a<b")
print (np.less (a,b))

a<b
[ True  True]


In [ ]:
print ("a<=b")
print (np.less_equal(a, b))

a<=b
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
0
0
([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [ ]:
arr= np.array ([1,2, 3, 4])
arr

array([1, 2, 3, 4])

In [ ]:
arr1=np.array([4, 6, 3, 8])
arr1

array([4, 6, 3, 8])

In [ ]:
np.intersect1d (arr, arr1)

array([3, 4])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
arrs= np.random.randn(7)
arrs

array([-0.99896131,  1.13953608,  1.75533415,  1.05640769,  0.74865205,
        1.65306172,  1.1955045 ])

In [ ]:
np.floor(arrs)

array([-1.,  1.,  1.,  1.,  0.,  1.,  1.])

In [ ]:
np.trunc(arrs)

array([-0.,  1.,  1.,  1.,  0.,  1.,  1.])

In [ ]:
arrs.astype(int)

array([0, 1, 1, 1, 0, 1, 1])

In [ ]:
arrs%arrs

array([-0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [ ]:
arr3d=np.array([np.arange(0,3),
                np.arange(0,3),
                np.arange(0,3)]).reshape (3, 3)
arr3d

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:
arr=np.random.rand(10)
arr

array([0.06755118, 0.54229003, 0.78690519, 0.95712831, 0.97890262,
       0.87905551, 0.83679432, 0.53433122, 0.3086191 , 0.17918211])

In [ ]:
arr.sort()
arr

array([0.06755118, 0.17918211, 0.3086191 , 0.53433122, 0.54229003,
       0.78690519, 0.83679432, 0.87905551, 0.95712831, 0.97890262])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [ ]:
A= np.random.rand(6)
A

array([0.38906477, 0.3362133 , 0.29627708, 0.76202721, 0.39334236,
       0.76927915])

In [ ]:
B=np.random.rand(6)
B

array([0.96258647, 0.51195936, 0.85301898, 0.45271855, 0.19976933,
       0.5009767 ])

In [ ]:
print (np.array_equal(A, B))

False


In [ ]:
print (np.allclose (A, B))

False


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [ ]:
a=np.arange (18).reshape (6, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
b=np.arange (12).reshape (3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.dot(a,b)

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218],
       [164, 203, 242, 281],
       [200, 248, 296, 344]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [ ]:
arr=np.random.randn(5)
arr

array([-0.08215321,  0.59430002,  0.48229412,  0.23346779, -0.02915737])

In [ ]:
arr[arr.argmax()]=0
print (arr)

[-0.08215321  0.          0.48229412  0.23346779 -0.02915737]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
today= np.datetime64 ("today", "D")
print ("Today:", today)

Today: 2023-12-06


In [ ]:
yesterday=np.datetime64 ("today", "D")
- np.timedelta64 (1, "D")

print (np.datetime64("today", "D") - np.timedelta64(1, "D"))

2023-12-05


In [ ]:
tomorrow=np.datetime64 ("today", "D")
+np.timedelta64(1, "D")

print (np.datetime64("today", "D") + np.timedelta64(1, "D"))

2023-12-07


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
print(np.arange("2016-01","2016-02", dtype="datetime64[D]"))

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [ ]:
a=np.random.randn (8)
a

array([-0.24179386, -1.4852621 ,  0.00760557, -1.16469513, -0.70437259,
       -0.237053  , -1.78651095,  0.38296754])

In [ ]:
a%a

array([-0., -0.,  0., -0., -0., -0., -0.,  0.])

In [ ]:
np.floor(a)

array([-1., -2.,  0., -2., -1., -1., -2.,  0.])

In [ ]:
a.astype(int)

array([ 0, -1,  0, -1,  0,  0, -1,  0])

In [ ]:
np.trunc(a)

array([-0., -1.,  0., -1., -0., -0., -1.,  0.])

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [ ]:
a=np.arange(4).reshape (2, 2)
a

array([[0, 1],
       [2, 3]])

In [ ]:
np.sum(a)

6

In [ ]:
np.add.reduce(a)

array([2, 4])

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [ ]:
arr=np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
p=3

In [ ]:
new_arr= np.zeros(len(arr) + (len(arr)  - 1) * (p))
new_arr [::p +1]= arr
print(new_arr)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [ ]:
a = np.arange(1, 15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
b=np.lib.stride_tricks.as_strided (a, shape=(11, 4), strides= (8, 8))
print (a, "\n", b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14] 
 [[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [ ]:
a=np.bincount(np.arange(6))
a

array([1, 1, 1, 1, 1, 1])

In [ ]:
b=np.bincount (np.array([1, 5, 3, 1, 4, 2]))
b

array([0, 2, 1, 1, 1, 1])

In [ ]:
np.intersect1d (a, b)

array([1])

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`